config/routes.rb
Hd4sq::Application.routes.draw do
  
  resource :user

	scope module: 'clients' do
		resources :foursquare_clients, only: ['new'], path: 'clients/foursquare' do
		  collection do
		    get 'callback'
		  end
		end
	end

  match '/checkins', :to => 'checkins#checkin', :via => 'POST'
  resources :itineraries
  root :to => 'users#new'
  resources :stops, :only => [:update, :destroy]

end

app/models/itinerary.rb
class Itinerary < ActiveRecord::Base
  has_many :stops
  belongs_to :foursquare_user
  attr_accessible :checkin_id, :foursquare_user_id, :approved, :demo,:zip,:tz_offset,:lat, :lng
  
  def to_s
    self.checkin_id
  end
  
  def to_reply
    sched = ''
    stops.each do |stop|
      #sched += stop.local_time_to_post.strftime('%l:%M%P')
      # sched += " - " +
      sched += stop.name + "\n"
    end   
    return sched
  end
  
  def lat_lng
    if self.lat && self.lng
      self.lat + "," + self.lng
    end
  end
  def self.create_itinerary_from_checkin(checkin, user)
    itin = self.new
    itin.foursquare_user = user
    itin.checkin_id = checkin['id']
    itin.demo = false
    itin.tz_offset = checkin['timeZoneOffset'].to_s.gsub(/(-?)(\d+)(\d{2})/, "\\1#{'\2'.rjust(3, '0')}:\\3")
    itin.lat = checkin['venue']['location']['lat'].to_s 
    itin.lng = checkin['venue']['location']['lng'].to_s
    itin.zip = checkin['venue']['zip']
    if checkin["shout"] && checkin['shout'] =~ /#demo/ 
      itin.demo = true 
    end
    if checkin["shout"] && checkin['shout'] =~ /#couch/
      itin.approved = true
    end
    itin.save
    itin.fill_it_out(0)
    return itin
  end
  
  def make_foursquare_stop(params, time, shout)
    url = "https://api.foursquare.com/v2/venues/explore?v=20130105&ll=#{self.lat_lng}&radius=2000&friendVisits=notvisited&oauth_token=#{self.foursquare_user.access_token}&#{params}"
    uri = URI.parse(url)
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true
    http.verify_mode = OpenSSL::SSL::VERIFY_NONE
    request = Net::HTTP::Get.new(uri.request_uri)
    response = http.request(request)
    result = JSON.parse(response.body)
    unless (result['response']['groups'] &&  result['response']['groups'][0]  && result['response']['groups'][0]['items'] && result['response']['groups'][0]['items'][0] && result['response']['groups'][0]['items'][0]['venue'])
      return
    end
    name = result['response']['groups'][0]['items'][0]['venue']['name']
    venue_id = result['response']['groups'][0]['items'][0]['venue']['id']
    lat_lng = result['response']['groups'][0]['items'][0]['venue']['location']['lat'].to_s + "," +result['response']['groups'][0]['items'][0]['venue']['location']['lng'].to_s 
    zip = result['response']['groups'][0]['items'][0]['venue']['location']['postalCode'].to_s
    self.stops.create({ :name => name, :time_to_post => time, :venue_id => venue_id, :shout => shout})
  end
  
  def make_jambase_stop(params, time, shout)
    #get jambase data

    if (self.zip)
      date = time.strftime('%m/%d/%y')
      url = "http://api.jambase.com/search?apikey=78hjynre9at8tk4grtq3fdz7&zip=#{self.zip}&radius=10&startDate=#{date}&endDate=#{date}&#{params}"
      xml_data = Net::HTTP.get_response(URI.parse(url)).body
      doc = REXML::Document.new(xml_data)
      venue_name = doc.elements['JamBase_Data/event/venue/venue_name'].text
      name = doc.elements['JamBase_Data/event/artists/artist/artist_name'].text + " @ " + venue_name
      venue_zip = doc.elements['JamBase_Data/event/venue/venue_zip'].text
    
      #match to foursq
      url = "https://api.foursquare.com/v2/venues/search?v=20130105&near=#{venue_zip}&query=#{ CGI.escape(venue_name)}&oauth_token=#{self.foursquare_user.access_token}"
      uri = URI.parse(url)
      http = Net::HTTP.new(uri.host, uri.port)
      http.use_ssl = true
      http.verify_mode = OpenSSL::SSL::VERIFY_NONE
      request = Net::HTTP::Get.new(uri.request_uri)
      response = http.request(request)
      result = JSON.parse(response.body)
      venue_id = result['response']['venues'][0]['id']
      self.stops.create({ :name => name, :time_to_post => time, :venue_id => venue_id, :shout => shout})
      
    else
      make_foursquare_stop("section=arts",time, shout)
    end
  end
  
  def fill_it_out(route)
    routes = YAML.load_file("#{Rails.root}/config/itineraries.yml")
    next_time = Time.now + 30.minutes
  
    routes[route]['path'].each do |stop|
      params = stop['params'] ? stop['params'] : ""
      shout_idx = Random.rand(stop['shouts'].length)
      shout = stop['shouts'][shout_idx]
      case stop['api']
      when 'foursquare'
        self.make_foursquare_stop(params, next_time, shout)
      when 'jambase'
        self.make_jambase_stop(params, next_time, shout)    
      end
      next_time =  next_time + (80 + Random.rand(40)).minutes
      
    end
    
  end
  
  def refill(route)
    self.stops.delete_all
    fill_it_out(route)
  end
  
end

app/controllers/itineraries_controller.rb
class ItinerariesController < ApplicationController
  layout "itineraries"
  def show
    @itinerary = Itinerary.find_by_checkin_id(params[:id])
    url = "https://api.instagram.com/v1/media/search?client_id=37d734676df34625a720f41c0da22479&lat=#{@itinerary.lat}&lng=#{@itinerary.lng}"
    uri = URI.parse(url)
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true
    @image = nil
    http.verify_mode = OpenSSL::SSL::VERIFY_NONE
    request = Net::HTTP::Get.new(uri.request_uri)
    begin
      response = http.request(request)
      result = JSON.parse(response.body)
      @image = { :src => result['data'][0]['images']['low_resolution']['url'], 
             :url => result['data'][0]['link'],
            :user => result['data'][0]['user']['username']}
    rescue
    end
  end
  
  def update
     @itinerary = Itinerary.find_by_checkin_id(params[:id])
     @itinerary.update_attributes(params[:itinerary])
     if (params['route'])
       @itinerary.refill(params['route'].to_i)
     end
     @itinerary.reload
     if (@itinerary.demo && @itinerary.approved? )
       @itinerary.stops.each do |stop|
         begin
           stop.check_in
         rescue
         end   
       end
       FollowUpMailer::follow_up(@itinerary).deliver
     end
     redirect_to itinerary_path(@itinerary.to_s)
  end
  
  def edit 
    @itinerary = Itinerary.find_by_checkin_id(params[:id])
    @routes = YAML.load_file("#{Rails.root}/config/itineraries.yml")
  end
end

app/views/itineraries/edit.html.erb
Select a new itinerary below
<%= form_for @itinerary, :url => itinerary_path(@itinerary.to_s) do |f| %>
  <% @routes.each_with_index do |route, index| %>
    <%= button_tag({ :name => "route", :value => index,  :class => 'btn' }) do  %>
      <%=route['name'] %>
    <% end %>
  <% end %>
<% end %>

    

app/views/itineraries/show.html.erb
<%= javascript_tag "var LAT_LNG = '#{ @itinerary.lat_lng }'; var FOURSQUARE_TOKEN = '#{@itinerary.foursquare_user.access_token}';" %>

<div class="content">
<% if @image %>  
  <%= link_to(image_tag(@image[:src], :class => 'instagram'), @image[:url]) %>
  <br/><%= @image[:user] %> just did that. Don't you want to get out there?
<% end %>
<% if @itinerary.approved? %>
  Your current "plans" 
<% else %>
  Your night's about to get a lot more interesting.
<% end %>
<% @itinerary.stops.each_with_index do |stop, index| %>
  <div class ="stop" data-id="<%= stop.id %>">
    <%= form_for stop do |f| %>
      <div class="note">
          <p><%= "Thing #{index + 1}" %></p>
          <div class="edit-options">
            <div class = "not-editing">
              <%= link_to raw('<i class="icon-edit icon-2x"></i>'), "#", :class => "edit-stop" %>
              <%= link_to raw('<i class="icon-trash icon-2x"></i>'), "#", :class => "delete-stop" %>
            </div>
            <div class= "editing">
              <%= link_to raw('<i class="icon-ok icon-2x"></i>'), "#", :class => "save-stop" %>
              <%= link_to raw('<i class="icon-remove icon-2x"></i>'), "#", :class => "cancel-stop" %>
            </div>
          </div>
        
      </div><!--/note-->
      <div class="checkin">
        <div class="title">
            <h2><%= stop.name %></h2>
        </div><!--/title-->
        <div class="content">
  	      <p><%= stop.shout %></p>
        </div><!--/content-->
      </div><!--/checkin-->
    <% end %>
  </div><!--/stop -->
<% end %>
    <% unless @itinerary.approved? %>
    <%= form_for @itinerary, :url => itinerary_path(@itinerary.to_s) do |f| %>
      <%= f.hidden_field(:approved, :value => "1") %>
      <%= f.submit({ :value => "Touch here to approve your itinerary!",  :class => 'btn' })  %>
    <% end %>

    <p class="cancel"><%=link_to "Not Feeling it?",edit_itinerary_path(@itinerary.to_s)%> </p>
      <%end%>
      
      </content>